version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: habit_tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: nastya2005
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - habit-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  habit-data-service:
    image: habit-tracker-data
    environment:
      - NODE_ENV=production
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=nastya2005
      - DB_NAME=habit_tracker
      - DB_PORT=5432
    networks:
      - habit-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  notification-service:
    image: habit-tracker-notification
    environment:
      - NODE_ENV=production
    networks:
      - habit-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  habit-tracker:
    image: habit-tracker-frontend
    networks:
      - habit-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  nginx:
    image: habit-tracker-nginx
    ports:
      - "80:80"
    networks:
      - habit-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

volumes:
  postgres_data:

networks:
  habit-network:
    driver: overlay